'use strict'

/**
 * The `stubs` command: generate a Druxt Entity wrapper component stub from
 * the view schema of a resource type and display mode.
 *
 * The generated file is the boilerplate a Druxt wrapper needs to be picked
 * up by DruxtEntity's wrapper resolution (`Druxt<EntityType><Bundle><Mode>`)
 * - one slot per schema field, ready to be themed. Start here, then move
 * fields into markup as needed.
 */

const pascalCase = (value) =>
  String(value)
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')

/**
 * Builds a wrapper stub's file contents from a view schema.
 *
 * @param {object} schema - A Druxt view schema
 *   (`{ id, resourceType, fields: [{ id, label, type, ... }] }`).
 *
 * @returns {string} The .vue file contents.
 */
const buildStub = (schema) => {
  const { entityType, bundle, mode } = schema.config
  const componentName = `DruxtEntity${pascalCase(entityType)}${pascalCase(bundle)}${pascalCase(mode)}`

  const lines = schema.fields
    .filter((field) => !!field.id)
    .map((field) => {
      const label = (field.label || {}).text || field.id
      const type = field.type || 'unknown'
      return `      <!-- ${label} (${type}) -->\n      <slot name="${field.id}" />`
    })
    .join('\n')

  return `<template>
  <div>
${lines}
  </div>
</template>

<script>
// Druxt Entity wrapper generated by druxt-inspect for schema '${schema.id}'.
// See https://druxtjs.org for theming documentation.
import { DruxtEntityMixin } from 'druxt-entity'

export default {
  name: '${componentName}',

  mixins: [DruxtEntityMixin],
}
</script>`
}

/**
 * Runs the `stubs` command.
 *
 * @param {{ schema: object }} clients - The Druxt clients.
 * @param {string} resourceType - The JSON:API resource type (`node--recipe`).
 * @param {object} [options] - Command options.
 * @param {string} [options.mode=default] - The display mode.
 *
 * @returns {object} `{ resourceType, mode, files: [{ filename, contents }] }`.
 *   Throws with available modes when no view schema matches.
 */
const stubs = async (clients, resourceType, options = {}) => {
  const { schema: runSchema } = require('./schema')
  const result = await runSchema(clients, resourceType, options)

  if (!result.view) {
    const modes = result.available.map((id) => id.split('--')[2]).filter((m, i, a) => a.indexOf(m) === i)
    throw new Error(`No '${result.mode}' view schema for ${resourceType}.` +
      (modes.length ? ` Available modes: ${modes.join(', ')}.` : ''))
  }

  const { entityType, bundle, mode } = result.view.config
  const filename = `DruxtEntity${pascalCase(entityType)}${pascalCase(bundle)}${pascalCase(mode)}.vue`

  return {
    resourceType,
    mode,
    files: [{ filename, contents: buildStub(result.view) }],
  }
}

/**
 * Renders the `stubs` command result as file blocks (used for stdout; the
 * `--output` option writes the actual files instead).
 *
 * @param {object} data - The command result.
 *
 * @returns {string} The human-readable output.
 */
const renderStubs = (data) =>
  data.files
    .map((file) => `${'#'.repeat(Math.max(8, file.filename.length + 4))}\n# ${file.filename}\n${'#'.repeat(Math.max(8, file.filename.length + 4))}\n\n${file.contents}`)
    .join('\n\n')

module.exports = { buildStub, renderStubs, stubs }
