image:
  file: .gitpod/Dockerfile

tasks:
  - before: git pull -f origin main:main || true
    init: |
      # DDev prebuild tasks
      .gitpod/scripts/ddev-download.sh
      .gitpod/scripts/ddev-setup.sh

      # Setup Drupal 9 backend
      .gitpod/scripts/drupal-setup.sh

      # druxt.js build install and build
      yarn install
      yarn build

      # druxtjs.org install
      cd $GITPOD_REPO_ROOT/docs && yarn
      cd $GITPOD_REPO_ROOT && yarn build:docs
    command: |
      cat .gitpod/WELCOME.md

# VScode xdebug extension
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - felixfbecker.php-debug
    - gruntfuggly.todo-tree
    - octref.vetur

ports:
  # Nuxt/Druxt
  - port: 3000
    visibility: public
  # Drupal
  - port: 8080
    visibility: public
  # Currently un-notified and unsupported mailhog http port
  # - port: 8025
  #   onOpen: ignore
  # # Currently un-notified and unsupported mailhog https port
  # - port: 8026
  #   onOpen: ignore
  # # Currently un-notified and unsupported phpmyadmin http port
  # - port: 8036
  #   onOpen: ignore
  # # Currently un-notified and unsupported phpmyadmin https port
  # - port: 8037
  #   onOpen: ignore
  # # router http port that we're ignoring.
  # - port: 8888
  #   onOpen: ignore
  # # router https port that we're ignoring.
  # - port: 8889
  #   onOpen: ignore
  # # xdebug port
  # - port: 9000
  #   onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: true
