docker-compose-yaml: ./docker-compose.yml

routes:
  insecure: Redirect

environments:
  main:
    routes:
      - app:
        - druxtjs.org
        - www.druxtjs.org
        - blocks.druxtjs.org
        - breadcrumb.druxtjs.org
        - entity.druxtjs.org
        - menu.druxtjs.org
        - router.druxtjs.org
        - schema.druxtjs.org
        - site.druxtjs.org
        - views.druxtjs.org
