version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:15.14

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install Codecov
          command: yarn add codecov

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found.
          - v1-dependencies-

      - run:
          name: Install
          command: yarn install

      - run:
          name: Build
          command: yarn build

      - run:
          name: Build docs
          command: yarn build:docs

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run lint
          command: yarn lint --format ./node_modules/eslint-junit/index.js
          environment:
            ESLINT_JUNIT_OUTPUT: ./reports/junit/eslint.xml

      - run:
          name: Renovate config validator
          command: yarn lint:renovate

      - run:
          name: Run tests
          command: yarn test --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
            NODE_OPTIONS: --max_old_space_size=8192

      - run:
          name: Upload coverage report
          command: yarn dlx codecov

      - run:
          name: Bundlewatch
          command: yarn bundlewatch

      - store_test_results:
          path: ./reports/junit/

      - store_artifacts:
          path: ./reports/junit

  # TODO - Fix CI deploy
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo

  #     - run:
  #         name: Authenticate with registry
  #         command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

  #     - run:
  #         name: Publish package
  #         command: npm publish

workflows:
  version: 2

  test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - build
      #       - test
      #     filters:
      #       branches:
      #         only: master
