version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: cimg/node:16.20.2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found.
          - v1-dependencies-

      - run:
          name: Install
          command: yarn install

      - run:
          name: Build
          command: yarn build

      - run:
          name: Build docs
          command: yarn build:docs

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run lint
          command: yarn lint --format ./node_modules/eslint-junit/index.js
          environment:
            ESLINT_JUNIT_OUTPUT: ./reports/junit/eslint.xml

      - run:
          name: Renovate config validator
          command: yarn lint:renovate

      - run:
          name: Bundlewatch
          command: yarn bundlewatch

  test_unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run unit tests
          command: yarn test:unit --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
            NODE_OPTIONS: --max_old_space_size=8192

      - run:
          name: Upload coverage report
          command: yarn dlx codecov

      - store_test_results:
          path: ./reports/junit/

      - store_artifacts:
          path: ./reports/junit

  test_e2e:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/repo
    environment:
      DDEV_NONINTERACTIVE: "true"
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Install ddev
          command: |
            curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh

      - run:
          name: Start server running
          command: |
            cd docs/drupal && ddev start -y

      - run:
          name: Install Drupal
          command: |
            cd docs/drupal && ddev drupal-install

      - run:
          name: Install cypress
          command: npx cypress install

      - run:
          name: Run DruxtSite end-to-end tests
          command: yarn start-server-and-test 'yarn example:druxt-site' http://localhost:3000 'npx cypress run --project examples/druxt-site/test --spec "examples/druxt-site/test/cypress/e2e/nuxt/*.cy.js" --record --tag examples-druxt-site'
      - run:
          name: Run DruxtSite storybook end-to-end tests
          command: yarn start-server-and-test 'yarn example:druxt-site:storybook --port 3000' http://localhost:3000 'npx cypress run --project examples/druxt-site/test --spec "examples/druxt-site/test/cypress/e2e/storybook/*.cy.js" --record --tag examples-druxt-site-storybook'
      - store_artifacts:
          path: ./examples/druxt-site/test/cypress/screenshots
      - store_artifacts:
          path: ./examples/druxt-site/test/cypress/videos

      - run:
          name: Run DruxtJS.org end-to-end tests
          command: yarn start-server-and-test docs:dev http://localhost:3000 'npx cypress run --project docs/nuxt/test --record --tag druxtjs.org'
      - store_artifacts:
          path: ./docs/nuxt/test/cypress/screenshots
      - store_artifacts:
          path: ./docs/nuxt/test/cypress/videos

  # TODO - Fix CI deploy
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo

  #     - run:
  #         name: Authenticate with registry
  #         command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

  #     - run:
  #         name: Publish package
  #         command: npm publish

workflows:
  version: 2

  test_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test_unit:
          requires:
            - build
      - test_e2e:
          requires:
            - build

      # - deploy:
      #     requires:
      #       - build
      #       - test
      #     filters:
      #       branches:
      #         only: master
