// Unlighthouse CI over the fixed route list, then its JSON read back.
import { readFile, writeFile, readdir, stat, mkdir } from 'node:fs/promises'
import { spawnSync } from 'node:child_process'
import { join } from 'node:path'
import { config } from './config.mjs'

export async function writeUnlighthouseConfig(example, outDir) {
  await mkdir(outDir, { recursive: true })
  const file = join(outDir, `unlighthouse.${example.name}.config.js`)
  const text = `// Generated by scripts/perf-audit for ${example.name}.
module.exports = {
  site: 'http://localhost:${example.port}',
  outputPath: ${JSON.stringify(join(outDir, 'unlighthouse'))},
  urls: ${JSON.stringify(example.routes)},
  scanner: { crawler: false, samples: 1 },
  puppeteerClusterOptions: { maxConcurrency: 1, timeout: 900000 },
  puppeteerOptions: {
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}),
  },
  ci: { budget: 0, reporter: 'jsonExpanded' },
}
`
  await writeFile(file, text)
  return file
}

function defaultSpawn(cmd, args, opts) {
  const result = spawnSync(cmd, args, { stdio: 'inherit', ...opts })
  return { exitCode: result.status }
}

export async function runUnlighthouse(example, outDir, { spawn = defaultSpawn, chromePath = process.env.CHROME_PATH } = {}) {
  const configFile = await writeUnlighthouseConfig(example, outDir)
  const args = ['--yes', `unlighthouse-ci@${config.unlighthouse.version}`, '--site', `http://localhost:${example.port}`, '--config-file', configFile, '--no-cache']
  const { exitCode } = spawn('npx', args, { env: { ...process.env, ...(chromePath ? { CHROME_PATH: chromePath } : {}) } })
  if (exitCode !== 0) throw new Error(`unlighthouse-ci exited with ${exitCode} for ${example.name}`)
}

async function findReports(dir, found = []) {
  for (const entry of await readdir(dir)) {
    const path = join(dir, entry)
    if ((await stat(path)).isDirectory()) await findReports(path, found)
    else if (entry === 'lighthouse.json') found.push(path)
  }
  return found
}

function postLoadApiCalls(report) {
  const items = report.audits?.['network-requests']?.details?.items || []
  const loaded = report.audits?.metrics?.details?.items?.[0]?.observedDomContentLoaded ?? 0
  return items.filter((item) => /\/(jsonapi|router)(\/|\?|$)/.test(new URL(item.url).pathname + '?') && item.startTime > loaded).length
}

export async function readUnlighthouseResults(outDir) {
  const ci = JSON.parse(await readFile(join(outDir, 'ci-result.json'), 'utf8'))
  const byRoute = {}
  const reports = {}
  for (const file of await findReports(outDir).catch(() => [])) {
    const report = JSON.parse(await readFile(file, 'utf8'))
    reports[new URL(report.requestedUrl).pathname] = report
  }
  for (const route of ci.routes) {
    const report = reports[route.path] || { audits: {} }
    const metric = (id) => route.metrics?.[id]?.numericValue
    byRoute[route.path] = {
      performance: Math.round((route.categories?.performance?.score ?? 0) * 100),
      lcpMs: Math.round(metric('largest-contentful-paint') ?? 0),
      clsScore: Number((metric('cumulative-layout-shift') ?? 0).toFixed(3)),
      tbtMs: Math.round(metric('total-blocking-time') ?? 0),
      fcpMs: Math.round(metric('first-contentful-paint') ?? 0),
      requests: report.audits?.['network-requests']?.details?.items?.length ?? 0,
      bytes: report.audits?.['total-byte-weight']?.numericValue ?? 0,
      postLoadApiCalls: postLoadApiCalls(report),
    }
  }
  return byRoute
}
