import consola from 'consola'
import dmd from 'dmd'
import fs from 'fs'
import globby from 'globby'
import jsdoc2md from 'jsdoc-to-markdown'
import mkdirp from 'mkdirp'
import ncp from 'ncp'
import path from 'path'
import vueDocs from 'vue-docgen-api'

const cwd = path.join(__dirname, '..')

/**
 * DruxtDocgen class.
 */
class DruxtDocgen {
  constructor() {
    this.components = []
    this.destination = 'docs/nuxt/content'
  }

  /**
   * Generate documentation for source JS and Vue files.
   */
  async generateDocs() {
    consola.info('Generating docs')

    /**
     * Generate API documents.
     */
    await this.generateApiDocs()

    /**
     * Generate list of packages.
     */
    await this.generatePackageList()

    /**
     * Generate list of components.
     */
    await this.generateComponentsList()

    /**
     * Generate the module page bodies from the package READMEs.
     */
    await this.generateModuleReadmes()

    /**
     * Copy external files to the generated files.
     */
    await this.copyFiles()
  }

  /**
   * Copy external files to the generated files.
   */
  async copyFiles() {
    consola.info('Copying files')

    // Changelogs. The H1 repeats the module header on the site, so it
    // comes off, as on the README mirror.
    const changelogs = await globby('packages/*/CHANGELOG.md')
    for (const file of changelogs) {
      const module = file.split('/')[1]
      const destination = `${this.destination}/api/packages/${module}/CHANGELOG.md`
      const content = fs.readFileSync(file, 'utf8').replace(/^# [^\n]+\n+/, '')
      mkdirp.sync(path.dirname(destination))
      fs.writeFileSync(destination, `---\ntitle: Release notes\n---\n\n${content}`)
    }

    // Contributing guide.
    await ncp('CONTRIBUTING.md', `${this.destination}/how-to/contributing.md`)
  }

  /**
   * Generate API documents.
   */
  async generateApiDocs() {
    consola.info('Generating API documents')

    const files = await globby([
      // Javascript.
      'packages/*/src/**/*.js',
      // Vue.js.
      'packages/*/src/components/**/*.vue',
      // Exclude fixtures, mocks and tests.
      '!**/__*__/**/*',
    ])

    for (const file of files) {
      // Get JSDoc template data from file.
      const templateData = jsdoc2md.getTemplateDataSync({
        configure: path.resolve(__dirname, '../jsdoc.json'),
        files: file,
      })

      // Process file based on extension.
      if (file.match(/\.js$/)) {
        await this.processJs(file, templateData)
      }
      else {
        this.components.push({ file, templateData })
        await this.processVue(file, templateData)
      }

      this.writeTemplateData(file, templateData)
    }
  }

  /**
   * Generate list of components.
   */
  async generateComponentsList() {
    consola.info('Generating components list')

    const components = this.components
      .filter((o) => o && o.file.split('/').length === 5 && o.templateData[0])
      .map(({ file, templateData }) =>
        `## ${templateData[0].name}

${templateData[0].description}

[Read the docs](/api/${file.replace('src/', '').replace('.vue', '')})
`)

    const destination = this.destination + '/api/components.md'
    mkdirp.sync(path.dirname(destination))

    fs.writeFileSync(destination, `---
title: Components
---
${components.join('\n* * *\n\n')}

* * *

_Note: The contents of this file where automatically generated by the [Druxt Docgen](https://github.com/druxt/druxt.js/tree/develop/packages/docgen)._
`)
  }

  /**
   * Generate pages under `modules/<package>/readme` from each public
   * package's README, so the site mirrors the npm README without drift.
   *
   * Emitted as `readme/index.md` (rather than `readme.md`) so the file
   * cannot collide with the hand-maintained `README.md` on
   * case-insensitive filesystems.
   */
  async generateModuleReadmes() {
    consola.info('Generating package README pages')

    const packageFiles = await globby('packages/*/package.json')
    const packages = packageFiles
      .map((file) => ({
        ...require(path.resolve(__dirname, '../../..', file)),
        __dir: file.split('/')[1],
      }))
      .filter((o) => !o.private && fs.existsSync(`packages/${o.__dir}/README.md`))

    for (const pkg of packages) {
      const source = fs.readFileSync(`packages/${pkg.__dir}/README.md`, 'utf8')

      // The README is the module page body, opening with the badges. The
      // banner, H1 and tagline repeat the module header, and the Links
      // block duplicates the site's own nav.
      const content = source
        .replace(/^\s*<img\b[^>]*src=["']\.\/(?:icon|banner)\.svg["'][^>]*>\s*/, '')
        .replace(/^# [^\n]+\n+/m, '')
        .replace(/^> [^\n]+\n+/m, '')
        .replace(/## Links\n(?:[-*] [^\n]+\n|\n)*/, '')
        // Site-relative links, so the reader stays in the app.
        .replace(/\]\(https:\/\/druxtjs\.org\//g, '](/')
        // Deprecations pages (except entity's) arrive with the docs
        // restructure; until then the crawler must not follow these links
        // into generated error pages, so they render as plain text.
        .replace(/\[([^\]]+)\]\(\/modules\/(?!entity\/)[a-z-]+\/deprecations\)/g, '$1')

      const title = pkg.__dir.charAt(0).toUpperCase() + pkg.__dir.slice(1)
      const description = ((source.match(/^> (.+)$/m) || [])[1] || '').replace(/:/g, ' -')
      const destination = `${this.destination}/modules/${pkg.__dir}/README.md`
      mkdirp.sync(path.dirname(destination))
      fs.writeFileSync(destination, `---
title: ${title.replace(/^Druxt(?=[A-Z])/, '')}
description: ${description}
---

${content.trim()}

* * *

_Note: The contents of this file were automatically generated from the [\`packages/${pkg.__dir}/README.md\`](https://github.com/druxt/druxt.js/tree/develop/packages/${pkg.__dir}/README.md)._
`)
    }
  }

  /**
   * Generate list of packages.
   */
  async generatePackageList() {
    consola.info('Generating package list')

    const packageFiles = await globby('packages/*/package.json')
    const packages = packageFiles
      // Load package data.
      .map((file) => ({
        ...require(path.resolve(__dirname, '../../..', file)),
        __dir: file.split('/')[1],
      }))
      // Filter and sort data
      .filter((o) => !o.private)
      .sort((a, b) => a.name < b.name ? -1 : 1)
      // Process package data.
      .map((pkg) =>
        `## ${pkg.name}

<div class="text-sm">

Version: [${pkg.version}](/api/packages/${pkg.__dir}/CHANGELOG)

</div>

${pkg.description}

[Read the docs](/api/packages/${pkg.__dir}/)
`)

    const destination = this.destination + '/api/README.md'
    mkdirp.sync(path.dirname(destination))

    fs.writeFileSync(destination, `---
title: Packages
---

${packages.join('\n* * *\n\n')}

* * *

_Note: The contents of this file where automatically generated by the [Druxt Docgen](https://github.com/druxt/druxt.js/tree/develop/packages/docgen)._
`)
  }

  /**
   * Process Javascript files.
   *
   * @param {string} file - The source file path.
   * @param {object[]} templateData - The JSDoc generated template data.
   */
  async processJs(file, templateData) {
    templateData.map(item => {
      // Vuex state scope fix.
      if (item.name === 'state' && item.scope === 'inner') {
        delete item.scope
      }

      // Vuex mutations/@mutator tag support.
      if (item.mutators) {
        item.description = item.mutators[0].description
        item.kind = 'method'
        item.scope = 'mutation'
      }
    })
  }

  /**
   * Process Vue.js files.
   *
   * @param {string} file - The source file path.
   * @param {object[]} templateData - The JSDoc generated template data.
   */
  async processVue(file, templateData) {
    // Get data from vue-docgen-api.
    const data = await vueDocs.parse(file, {
      alias: {
        druxt: path.resolve('packages/druxt')
      }
    })

    // Inject extends from vue-docgen-api into jsdoc data.
    const prefixId = (templateData[0] || {}).id || ''
    // Props.
    for (const prop of (data.props || []).filter((prop) => !templateData.map((o) => o.id).includes(`${prefixId}.props.${prop.name}`))) {
      const item = {
        id: `${prefixId}.props.${prop.name}`,
        longname: `${prefixId}.props.${prop.name}`,
        name: prop.name,
        kind: 'member',
        scope: 'static',
        description: prop.description,
        memberof: `${prefixId}.props`,
      }
      if ((prop.tags || {}).example) {
        item.examples = [prop.tags.example[0].description.replace('DruxtModule', prefixId.split(':')[1])]
      }
      templateData.push(item)
    }

    templateData.map(item => {
      const parts = item.id.split('.')
      if (item.memberof === null && parts.length > 1) {
        parts.pop()
        item.memberof = parts.join('.')
      }

      // @vue-computed tag support.
      if (item._vueComputed) {
        // Strip out HTML table from description.
        item.description = item.description.replace(/<\/p.*/ms, '')

        item._vueComputed.map(property => {
          templateData.push({
            id: `module:${data.displayName}.computed.${property.name}`,
            longname: `module:${data.displayName}.computed.${property.name}`,
            kind: 'property',
            scope: 'static',
            memberof: `module:${data.displayName}.computed`,

            ...property
          })
        })
      }

      // Vue.js Computed properties fixes.
      if (parts[1] === 'computed' && parts.length === 2) {
        item.kind = 'property'
      }
    })
  }

  /**
   * Write template data to file system.
   *
   * @param {string} file - The file name.
   * @param {object[]} templateData - The JSDoc / Vuedoc generated data.
   */
  writeTemplateData(file, templateData) {
    if (!templateData) return

    const content = dmd(templateData, {
      'example-lang': 'vue live',
      'heading-depth': 1,
      partial: [
        path.resolve(cwd, 'partials/sig-name.hbs')
      ],
      separators: true
    })
    if (!content) return

    const destination = `${this.destination}/api/${file.replace('src/', '').replace(/\.[^/.]+$/, '.md')}`
    mkdirp.sync(path.dirname(destination))

    // Build frontmatter. A package's index is titled after the package, not
    // after whichever symbol jsdoc happened to document first: `site/index.js`
    // would otherwise render as "DruxtSiteMixin", naming one export rather
    // than the package entry point, and diverging from the module docs.
    const packageIndex = file.match(/^packages\/([^/]+)\/src\/index\.[cm]?js$/)
    const name = packageIndex
      ? packageIndex[1].charAt(0).toUpperCase() + packageIndex[1].slice(1)
      : templateData[0].id.split(':').pop()

    const frontmatter = `---\ntitle: ${name}\n---\n\n`

    fs.writeFileSync(destination, frontmatter + content)
  }
}

export { DruxtDocgen }
