import consola from 'consola'
import dmd from 'dmd'
import fs from 'fs'
import globby from 'globby'
import jsdoc2md from 'jsdoc-to-markdown'
import mkdirp from 'mkdirp'
import ncp from 'ncp'
import path from 'path'
import vueDocs from 'vue-docgen-api'

const cwd = path.join(__dirname, '..')

/**
 * DruxtDocgen class.
 */
class DruxtDocgen {
  constructor() {
    this.components = []
    this.destination = 'docs/nuxt/content'
    this.apiPages = []
    this.inheritedTypes = {}
  }

  /**
   * Generate documentation for source JS and Vue files.
   */
  async generateDocs() {
    consola.info('Generating docs')

    /**
     * Generate API documents.
     */
    await this.generateApiDocs()

    /**
     * Generate list of packages.
     */
    await this.generatePackageList()

    /**
     * Generate list of components.
     */
    await this.generateComponentsList()

    /**
     * Generate the module page bodies from the package READMEs.
     */
    await this.generateModuleReadmes()

    /**
     * Copy external files to the generated files.
     */
    await this.copyFiles()
  }

  /**
   * Copy external files to the generated files.
   */
  async copyFiles() {
    consola.info('Copying files')

    // Changelogs. The H1 repeats the module header on the site, so it
    // comes off, as on the README mirror.
    const changelogs = await globby('packages/*/CHANGELOG.md')
    for (const file of changelogs) {
      const module = file.split('/')[1]
      const destination = `${this.destination}/api/packages/${module}/CHANGELOG.md`
      const content = fs.readFileSync(file, 'utf8').replace(/^# [^\n]+\n+/, '')
      mkdirp.sync(path.dirname(destination))
      fs.writeFileSync(destination, `---\ntitle: Release notes\n---\n\n${content}`)
    }

    // Contributing guide.
    await ncp('CONTRIBUTING.md', `${this.destination}/how-to/contributing.md`)
  }

  /**
   * Generate API documents.
   */
  async generateApiDocs() {
    consola.info('Generating API documents')

    this.apiPages = []
    this.inheritedTypes = {}

    const files = await globby([
      // Javascript.
      'packages/*/src/**/*.js',
      // Vue.js.
      'packages/*/src/components/**/*.vue',
      // Exclude fixtures, mocks and tests.
      '!**/__*__/**/*',
      // docgen and test-utils are internal tooling, not public API surface.
      '!packages/docgen/**',
      '!packages/test-utils/**',
    ])

    for (const file of files) {
      // Get JSDoc template data from file.
      const templateData = jsdoc2md.getTemplateDataSync({
        configure: path.resolve(__dirname, '../jsdoc.json'),
        files: file,
      })

      // Process file based on extension.
      if (file.match(/\.js$/)) {
        await this.processJs(file, templateData)
      }
      else {
        this.components.push({ file, templateData })
        await this.processVue(file, templateData)
      }

      this.writeTemplateData(file, templateData)
    }

    this.flushApiPages()
  }

  /**
   * Generate list of components.
   */
  async generateComponentsList() {
    consola.info('Generating components list')

    const components = this.components
      .filter((o) => o && o.file.split('/').length === 5 && o.templateData[0])
      .map(({ file, templateData }) =>
        [`## ${templateData[0].name}`, templateData[0].description, `[Read the docs](/api/${file.replace('src/', '').replace('.vue', '')})`]
          .filter(Boolean)
          .join('\n\n')
      )

    const destination = this.destination + '/components/README.md'
    mkdirp.sync(path.dirname(destination))

    fs.writeFileSync(destination, `---
title: Components
---
${components.map((o) => o.trim()).join('\n\n* * *\n\n')}

* * *

_Note: The contents of this file were automatically generated by the [Druxt Docgen](https://github.com/druxt/druxt.js/tree/develop/packages/docgen)._
`)
  }

  /**
   * Generate the module page bodies (`modules/<package>/README.md`) from
   * each public package's README, so the site mirrors the npm README
   * without drift.
   */
  async generateModuleReadmes() {
    consola.info('Generating package README pages')

    const packageFiles = await globby('packages/*/package.json')
    const packages = packageFiles
      .map((file) => ({
        ...require(path.resolve(__dirname, '../../..', file)),
        __dir: file.split('/')[1],
      }))
      .filter((o) => !o.private && fs.existsSync(`packages/${o.__dir}/README.md`))

    for (const pkg of packages) {
      const source = fs.readFileSync(`packages/${pkg.__dir}/README.md`, 'utf8')

      // The README is the module page body, opening with the badges. The
      // banner, H1 and tagline repeat the module header, and the Links
      // block duplicates the site's own nav.
      const content = source
        .replace(/^\s*<img\b[^>]*src=["']\.\/(?:icon|banner)\.svg["'][^>]*>\s*/, '')
        .replace(/^# [^\n]+\n+/m, '')
        .replace(/^> [^\n]+\n+/m, '')
        .replace(/## Links\n(?:[-*] [^\n]+\n|\n)*/, '')
        // Site-relative links, so the reader stays in the app.
        .replace(/\]\(https:\/\/druxtjs\.org\//g, '](/')

      const title = pkg.__dir.charAt(0).toUpperCase() + pkg.__dir.slice(1)
      const description = ((source.match(/^> (.+)$/m) || [])[1] || '').replace(/'/g, "''")
      const destination = `${this.destination}/modules/${pkg.__dir}/README.md`
      mkdirp.sync(path.dirname(destination))
      fs.writeFileSync(destination, `---
title: ${title.replace(/^Druxt(?=[A-Z])/, '')}
description: '${description}'
---

${content.trim()}

* * *

_Note: The contents of this file were automatically generated from the [\`packages/${pkg.__dir}/README.md\`](https://github.com/druxt/druxt.js/tree/develop/packages/${pkg.__dir}/README.md)._
`)
    }
  }

  /**
   * Generate list of packages.
   */
  async generatePackageList() {
    consola.info('Generating package list')

    const packageFiles = await globby('packages/*/package.json')
    const packages = packageFiles
      // Load package data.
      .map((file) => ({
        ...require(path.resolve(__dirname, '../../..', file)),
        __dir: file.split('/')[1],
      }))
      // Filter and sort data
      .filter((o) => !o.private)
      .sort((a, b) => a.name < b.name ? -1 : 1)
      // Process package data.
      .map((pkg) =>
        `## ${pkg.name}

<div class="text-sm">

Version: [${pkg.version}](/api/packages/${pkg.__dir}/CHANGELOG)

</div>

${pkg.description}

[Read the docs](/api/packages/${pkg.__dir}/)
`)

    const destination = this.destination + '/api/README.md'
    mkdirp.sync(path.dirname(destination))

    fs.writeFileSync(destination, `---
title: Packages
---

${packages.join('\n* * *\n\n')}

* * *

_Note: The contents of this file were automatically generated by the [Druxt Docgen](https://github.com/druxt/druxt.js/tree/develop/packages/docgen)._
`)
  }

  /**
   * Process Javascript files.
   *
   * @param {string} file - The source file path.
   * @param {object[]} templateData - The JSDoc generated template data.
   */
  async processJs(file, templateData) {
    templateData.map(item => {
      // Vuex state/getter scope fix: jsdoc marks them inner, and the inner
      // scope prefixes a literal `~` onto their headings.
      if (item.scope === 'inner' && (item.name === 'state' || /\/stores\//.test(file))) {
        delete item.scope
      }

      // Vuex mutations/@mutator tag support.
      if (item.mutators) {
        item.description = item.mutators[0].description
        item.kind = 'method'
        item.scope = 'mutation'
      }
    })
  }

  /**
   * Process Vue.js files.
   *
   * @param {string} file - The source file path.
   * @param {object[]} templateData - The JSDoc generated template data.
   */
  async processVue(file, templateData) {
    // Get data from vue-docgen-api.
    const data = await vueDocs.parse(file, {
      alias: {
        druxt: path.resolve('packages/druxt')
      }
    })

    // Synthesize the module item for components without their own top-level
    // JSDoc block (e.g. DruxtRouterEntity), so injected members re-id under a
    // proper prefix and dmd renders a page.
    if (!templateData.length) {
      const componentName = path.basename(file, '.vue')
      templateData.push({
        id: `module:${componentName}`,
        longname: `module:${componentName}`,
        name: componentName,
        kind: 'module',
        description: '',
      })
    }

    // Inject extends from vue-docgen-api into jsdoc data.
    const prefixId = (templateData[0] || {}).id || ''
    // Props.
    for (const prop of (data.props || []).filter((prop) => !templateData.map((o) => o.id).includes(`${prefixId}.props.${prop.name}`))) {
      const type = prop.type || {}
      const typeNames = (type.elements || [type]).map((o) => o.name).filter(Boolean)
      const item = {
        id: `${prefixId}.props.${prop.name}`,
        longname: `${prefixId}.props.${prop.name}`,
        name: prop.name,
        kind: 'member',
        scope: 'static',
        description: prop.description,
        memberof: `${prefixId}.props`,
      }
      if (typeNames.length) {
        item.type = { names: typeNames }
      }
      // vue-docgen gives the default as raw source text; `undefined` is the
      // absence of a default, and literals must not render as quoted strings.
      if (prop.defaultValue && prop.defaultValue.value !== 'undefined') {
        const raw = prop.defaultValue.value.replace(/^'(.*)'$/, '$1')
        try {
          item.defaultvalue = JSON.parse(raw)
        } catch (e) {
          item.defaultvalue = raw
        }
      }
      if ((prop.tags || {}).example) {
        // Pre-fence as plain vue: a bare element with only this prop is not
        // a runnable example, and the default example-lang would render it
        // live on every extending component's page.
        const text = prop.tags.example[0].description.replace('DruxtModule', prefixId.split(':')[1])
        item.examples = [text.includes('```') ? text : '```vue\n' + text + '\n```']
      }
      templateData.push(item)
    }

    // Ensure the props container exists so dmd renders static prop members
    // (jsdoc only creates it when the file documents props inline).
    if ((data.props || []).length && !templateData.map((o) => o.id).includes(`${prefixId}.props`)) {
      templateData.push({
        id: `${prefixId}.props`,
        longname: `${prefixId}.props`,
        name: 'props',
        kind: 'member',
        scope: 'static',
        memberof: prefixId,
      })
    }

    // Inject inherited mixin/extends members via the jsdoc pipeline, as
    // vue-docgen-api does not reliably resolve them across packages.
    await this.injectMixinMembers(file, templateData, prefixId)

    templateData.map(item => {
      const parts = item.id.split('.')
      if (item.memberof === null && parts.length > 1) {
        parts.pop()
        item.memberof = parts.join('.')
      }

      // @vue-computed tag support.
      if (item._vueComputed) {
        // Strip out HTML table from description.
        item.description = item.description.replace(/<\/p.*/ms, '')

        item._vueComputed.map(property => {
          templateData.push({
            id: `module:${data.displayName}.computed.${property.name}`,
            longname: `module:${data.displayName}.computed.${property.name}`,
            kind: 'property',
            scope: 'static',
            memberof: `module:${data.displayName}.computed`,

            ...property
          })
        })
      }

      // Vue.js Computed properties fixes.
      if (parts[1] === 'computed' && parts.length === 2) {
        item.kind = 'property'
      }
    })

  }

  /**
   * Order members for rendering: injected members join their scope group
   * (dmd re-opened the group further down otherwise), and deprecated
   * members sink below the live ones within each group.
   *
   * @param {object[]} templateData - The JSDoc generated template data.
   */
  orderMembers(templateData) {
    const groupKey = (item) => `${item.memberof || ''}|${item.scope || ''}`
    const firstSeen = new Map()
    templateData.forEach((item, i) => {
      if (!firstSeen.has(groupKey(item))) firstSeen.set(groupKey(item), i)
    })
    const indexed = templateData.map((item, i) => [item, i])
    indexed.sort((a, b) =>
      (firstSeen.get(groupKey(a[0])) - firstSeen.get(groupKey(b[0])))
      || ((a[0].deprecated !== undefined) - (b[0].deprecated !== undefined))
      || (a[1] - b[1]))
    templateData.splice(0, templateData.length, ...indexed.map((o) => o[0]))
  }

  /**
   * Inject inherited mixin members into template data.
   *
   * Finds `extends` / `mixins` references in the component script, resolves
   * them to their source files within the monorepo, and merges their JSDoc
   * template data under the consuming component's id.
   *
   * @param {string} file - The source file path.
   * @param {object[]} templateData - The JSDoc generated template data.
   * @param {string} prefixId - The consuming component's JSDoc id.
   */
  async injectMixinMembers(file, templateData, prefixId) {
    if (!fs.existsSync(file)) return

    let script = (fs.readFileSync(file, 'utf8').match(/<script[^>]*>([\s\S]*)<\/script\b[^>]*>/i) || [])[1]
    if (!script) return
    // Strip block comments before matching: an `extends:` inside a JSDoc
    // @example otherwise resolves as a phantom parent.
    script = script.replace(/\/\*[\s\S]*?\*\//g, '')

    // Collect extends/mixins identifiers.
    const identifiers = []
    const extendsMatch = script.match(/extends:\s*([A-Za-z0-9_$]+)/)
    if (extendsMatch) identifiers.push(extendsMatch[1])
    const mixinsMatch = script.match(/mixins:\s*\[([^\]]*)\]/)
    if (mixinsMatch) {
      mixinsMatch[1].split(',').map((o) => o.trim()).filter(Boolean).forEach((o) => identifiers.push(o))
    }

    const existingIds = templateData.map((o) => o.id)
    for (const identifier of identifiers) {
      // Resolve the identifier's import specifier.
      const importMatch = script.match(new RegExp(`import\\s+\\{?[^};\\n]*\\b${identifier}\\b[^};\\n]*\\}?\\s+from\\s+['"]([^'"]+)['"]`))
      if (!importMatch) continue
      const specifier = importMatch[1]

      // Map the import specifier to monorepo source files.
      let files = []
      if (specifier.startsWith('druxt/dist/')) {
        files = [specifier.replace('druxt/dist/', 'packages/druxt/src/')]
      }
      else if (/^druxt(-[a-z]+)?$/.test(specifier)) {
        // Bare 'druxt' is the core package; 'druxt-<name>' maps to its directory.
        const module = specifier === 'druxt' ? 'druxt' : specifier.replace(/^druxt-/, '')
        files = await globby(`packages/${module}/src/mixins/*.js`)
      }
      else if (specifier.startsWith('.')) {
        // Relative specifier, resolved against the consuming file's directory.
        const resolved = path.join(path.dirname(file), specifier)
        files = [resolved, `${resolved}.vue`, `${resolved}.js`].filter((o) => fs.existsSync(o)).slice(0, 1)
      }
      if (!files.length) {
        // Warn rather than skip silently: an unresolved parent means missing docs.
        consola.warn(`[docgen] ${file}: cannot resolve '${identifier}' from '${specifier}', inherited members not documented`)
        continue
      }

      for (const mixinFile of files) {
        const mixinData = jsdoc2md.getTemplateDataSync({
          configure: path.resolve(__dirname, '../jsdoc.json'),
          files: mixinFile,
        })

        for (const item of mixinData) {
          // Only items belonging to the referenced mixin, plus typedefs.
          const prefix = item.id.startsWith('module:') ? `module:${identifier}.` : `${identifier}.`
          const isTypedef = item.kind === 'typedef'
          const remainder = item.id.startsWith(prefix) ? item.id.slice(prefix.length) : null
          if (!isTypedef && !remainder) continue

          // Skip container members; the consuming component defines its own.
          if (remainder && /^(props|methods|computed)$/.test(remainder) && item.kind === 'member') {
            const containerId = `${prefixId}.${remainder}`
            if (!existingIds.includes(containerId)) {
              existingIds.push(containerId)
              templateData.push({
                ...item,
                id: containerId,
                longname: containerId,
                memberof: prefixId,
              })
            }
            continue
          }

          if (isTypedef) {
            // Typedefs inherited from another package (DruxtModule's, for
            // every consuming component) are documented once on their own
            // page; re-emitting them added ~87 duplicate sections. Record
            // the inheritance for a links line instead.
            const consumingPkg = (file.match(/^packages\/([^/]+)\//) || [])[1]
            const sourcePkg = (mixinFile.match(/^packages\/([^/]+)\//) || [])[1]
            if (sourcePkg && consumingPkg && sourcePkg !== consumingPkg) {
              const record = this.inheritedTypes[file] = this.inheritedTypes[file] || { source: identifier, names: [] }
              if (!record.names.includes(item.name)) record.names.push(item.name)
              continue
            }
            if (!existingIds.includes(item.id)) {
              templateData.push(item)
              existingIds.push(item.id)
            }
            continue
          }

          // Re-id the item under the consuming component.
          const id = `${prefixId}.${remainder}`
          if (existingIds.includes(id)) continue

          // `value` is documented as `v-model` by vue-docgen-api; skip the
          // duplicate when the friendly name is already present.
          if (remainder === 'props.value' && existingIds.includes(`${prefixId}.props.v-model`)) continue

          templateData.push({
            ...item,
            id,
            longname: id,
            memberof: item.memberof && item.memberof.startsWith(prefix)
              ? `${prefixId}.${item.memberof.slice(prefix.length)}`
              : prefixId,
          })
          existingIds.push(id)
        }
      }
    }
  }

  /**
   * Write template data to file system.
   *
   * @param {string} file - The file name.
   * @param {object[]} templateData - The JSDoc / Vuedoc generated data.
   */
  writeTemplateData(file, templateData) {
    if (!templateData) return

    this.orderMembers(templateData)

    let content = dmd(templateData, {
      'example-lang': 'vue live',
      // The page header renders the frontmatter title as the h1, so body
      // headings start at h2; depth 1 gave every page up to ten h1s.
      'heading-depth': 2,
      // The defaults opened 42 pages with a raw kind-index dump before
      // any real content; the curated package indexes replace them.
      'global-index-format': 'none',
      'module-index-format': 'none',
      partial: [
        path.resolve(cwd, 'partials/sig-name.hbs'),
        // dmd's own partial prints a bare "***Deprecated***" and drops the
        // tag's text, which is where the version, removal target and
        // replacement live. `deprecated.length` distinguishes a text tag from
        // a bare `@deprecated` (true), which has no length.
        path.resolve(cwd, 'partials/deprecated.hbs')
      ],
      separators: true
    })
    if (!content) return

    const destination = `${this.destination}/api/${file.replace('src/', '').replace(/\.[^/.]+$/, '.md')}`

    // Build frontmatter. A package's index is titled after the package, not
    // after whichever symbol jsdoc happened to document first: `site/index.js`
    // would otherwise render as "DruxtSiteMixin", naming one export rather
    // than the package entry point, and diverging from the module docs.
    const packageIndex = file.match(/^packages\/([^/]+)\/src\/index\.[cm]?js$/)
    // Sub-directory indexes are titled after their role, stores after their
    // exported class, and constructor parens never reach a title.
    const subIndex = file.match(/^packages\/([^/]+)\/src\/([^/]+)\/index\.[cm]?js$/)
    const storeFile = file.match(/^packages\/([^/]+)\/src\/stores\//)
    const cap = (o) => o.charAt(0).toUpperCase() + o.slice(1)
    let name
    if (packageIndex) {
      name = cap(packageIndex[1])
    }
    else if (subIndex && subIndex[2] !== 'nuxt') {
      name = `${cap(subIndex[1])} ${subIndex[2]}`
    }
    else if (storeFile) {
      const pkg = storeFile[1]
      name = pkg === 'druxt' ? 'DruxtStore' : `Druxt${cap(pkg)}Store`
    }
    else {
      // Includes `src/nuxt/index.js` module pages, which are titled after
      // their documented symbol rather than their directory.
      name = templateData[0].id.split(':').pop().replace(/\(\)$/, '')
    }

    // Store pages: jsdoc titles them after the Vuex namespace (`druxt`,
    // `druxt/views`), which reads as a broken heading against the
    // DruxtStore-style page title. Head with the title, keep the namespace.
    if (storeFile) {
      content = content.replace(/^## ([^\n]+)$/m, (m, namespace) =>
        `## ${name}\n\nVuex module, registered under the \`${namespace.trim()}\` namespace.`)
    }

    // Deprecation, for consumers that only read frontmatter (API index, search,
    // recent documents). Flag the page only when the documented symbol itself
    // carries @deprecated, not when a member does: jsdoc splits a class into
    // `Foo()` (constructor, the root) and `Foo` (the class, which holds the
    // tag), so match on the root id with any constructor parens stripped. A
    // page whose members are deprecated but whose symbol is live is not
    // deprecated.
    const rootId = templateData[0].id.replace(/\(\)$/, '')
    const deprecated = templateData.some((o) => o.id === rootId && o.deprecated !== undefined)

    const frontmatter = [
      '---',
      `title: ${name}`,
      ...(deprecated ? ['deprecated: true'] : []),
      '---',
      '',
      '',
    ].join('\n')

    this.apiPages.push({ file, destination, frontmatter, content, title: name, deprecated })
  }

  /**
   * Resolve links, weave inherited-type references, build the curated
   * package indexes, and write every buffered API page.
   */
  flushApiPages() {
    const routeOf = (destination) => destination
      .slice(this.destination.length)
      .replace(/\.md$/, '')
      .replace(/\/index$/, '')
    const routes = new Set(this.apiPages.map((o) => routeOf(o.destination)))

    // Same title on two pages (menu and site both export a ModuleOptions
    // typedef) is ambiguous in search and navigation; suffix the package.
    const byTitle = new Map()
    for (const page of this.apiPages) {
      if (!byTitle.has(page.title)) byTitle.set(page.title, [])
      byTitle.get(page.title).push(page)
    }
    for (const pages of byTitle.values()) {
      if (pages.length < 2) continue
      for (const page of pages) {
        const pkg = (page.file.match(/^packages\/([^/]+)\//) || [])[1]
        page.title = `${page.title} (${pkg === 'druxt' ? 'druxt' : `druxt-${pkg}`})`
        page.frontmatter = page.frontmatter.replace(/^title: .*$/m, `title: ${page.title}`)
      }
    }
    const titleOf = new Map(this.apiPages.map((o) => [routeOf(o.destination), o.title]))

    for (const page of this.apiPages) {
      // Relative links were authored against the page's directory.
      const baseDir = path.posix.dirname(routeOf(page.destination) + (page.destination.endsWith('/index.md') ? '/index' : ''))

      page.content = page.content
        // Strip Todo blocks; internal task state is not reference content.
        .replace(/\*\*Todo\*\*\n\n(?:[-*] \[[ x]\] .*\n?)+/g, '')
        // Root every druxtjs.org link so navigation stays on the serving
        // origin (site, preview or tunnel alike).
        .replace(/\]\(https?:\/\/druxtjs\.org(\/[^)#]*)?((?:#[^)]*)?)\)/g, (match, target, hash) => `](${target || '/'}${hash})`)
        // Resolve every relative link against the page's own route.
        .replace(/\]\((\.\.?\/[^)#]+|\.\.?)((?:#[^)]*)?)\)/g, (match, target, hash) => {
          const resolved = path.posix.resolve(baseDir, target)
          return `](${resolved}${hash})`
        })
        // A label that is itself a URL reads as a broken link; use the
        // target page's title.
        .replace(/\[https?:\/\/druxtjs\.org\/api\/[^\]]+\]\((\/api\/[^)#]+)((?:#[^)]*)?)\)/g, (match, target, hash) => {
          const title = titleOf.get(target.replace(/\/$/, ''))
          return title ? `[${title}](${target}${hash})` : match
        })
        // Link bare URLs on See lines; unlabeled @see tags render as
        // plain text next to their labeled siblings otherwise.
        .replace(/^(\*\*See\*\*: |- )(https?:\/\/[^\s<>`]+)([ \t]*)$/gm, (match, pre, url, trail) => {
          const internal = (url.match(/^https?:\/\/druxtjs\.org(\/[^\s#?]*)?/) || [])[1]
          const target = internal && internal.replace(/\/$/, '')
          const label = (target && titleOf.get(target)) || (internal || url.replace(/^https?:\/\//, ''))
          return `${pre}[${label}](${internal ? (target || '/') : url})${trail}`
        })
        // The deprecation tag text was written to follow "Deprecated:";
        // smooth the joint now that the colon is gone.
        .replace(/\*\*\*Deprecated\*\*\* in ([^\n]*?) and is removed from /g, '***Deprecated*** in $1, removed from ')
        // Empty inherited container sections: a heading and a Kind line
        // with no members is generator noise, not documentation.
        .replace(/\n#{3,5} \.(props|methods|computed)\n\n\*\*Kind\*\*: [^\n]+\n\n\* \* \*\n/g, '\n')
        // An SFC comment cannot contain a literal closing script tag, so
        // examples omit it; close the fence for copy-paste correctness.
        .replace(/```(vue live|vue|js)\n([\s\S]*?)```/g, (match, lang, body) => {
          if (/<script[\s>]/i.test(body) && !/<\/script\b[^>]*>/i.test(body)) {
            return '```' + lang + '\n' + body.replace(/\n*$/, '\n') + '</script>\n```'
          }
          return match
        })
        // dmd escapes underscores and quotes into headings; unescape so
        // member names read as written.
        .replace(/^(#{2,6} .*)$/gm, (m) => m
          .replace(/\\_/g, '_')
          .replace(/&#x27;/g, "'")
          .replace(/&#x3D;/g, '=')
          .replace(/&gt;/g, '>'))

      // Warn on any absolute API link with no page behind it; these are
      // source-level defects for the per-package passes.
      const seen = new Set()
      for (const m of page.content.matchAll(/\]\((\/api\/[^)#]+)/g)) {
        const target = m[1].replace(/\/$/, '')
        if (!routes.has(target) && !seen.has(target)) {
          seen.add(target)
          consola.warn(`[docgen] ${page.file}: link target has no page: ${target}`)
        }
      }

      // Inherited types, as links to their defining page.
      const inherited = this.inheritedTypes[page.file]
      if (inherited && inherited.names.length) {
        page.content += [
          '',
          '## Inherited type definitions',
          '',
          `Inherited from [${inherited.source}](/api/packages/druxt/components/DruxtModule): ` +
            inherited.names.sort().map((o) => `\`${o}\``).join(', ') + '.',
          '',
        ].join('\n')
      }
    }

    // Curated package indexes: a grouped, linked listing per package.
    const kindOf = (route) => {
      if (route.includes('/components/')) return 'Components'
      if (route.includes('/mixins/')) return 'Mixins'
      if (route.includes('/stores/')) return 'Stores'
      if (route.includes('/typedefs/')) return 'Type definitions'
      if (route.endsWith('/nuxt') || route.endsWith('/nuxtModule')) return 'Nuxt module'
      return 'Modules and classes'
    }
    const order = ['Nuxt module', 'Components', 'Modules and classes', 'Stores', 'Mixins', 'Type definitions']
    for (const page of this.apiPages) {
      const packageIndex = page.file.match(/^packages\/([^/]+)\/src\/index\.[cm]?js$/)
      if (!packageIndex) continue
      const pkg = packageIndex[1]
      const groups = new Map()
      const deprecatedPages = []
      for (const other of this.apiPages) {
        if (other === page || !other.file.startsWith(`packages/${pkg}/src/`)) continue
        // Aggregate directory indexes duplicate this listing, except the
        // Nuxt module entry point, which some packages keep at
        // `src/nuxt/index.js` and would otherwise be unreachable.
        if (/\/index\.[cm]?js$/.test(other.file) && !/\/nuxt\/index\.[cm]?js$/.test(other.file)) continue
        const route = routeOf(other.destination)
        const kind = kindOf(route)
        // Deprecated pages sit in a de-emphasized trailing section rather
        // than crowding the live surface.
        if (other.deprecated) {
          const label = { 'Components': 'component', 'Mixins': 'mixin', 'Stores': 'store', 'Type definitions': 'typedef' }[kind]
          deprecatedPages.push({ title: other.title, line: `- [${other.title}](${route})${label ? ` (${label})` : ''}` })
          continue
        }
        if (!groups.has(kind)) groups.set(kind, [])
        groups.get(kind).push({ title: other.title, line: `- [${other.title}](${route})` })
      }
      const sections = order
        .filter((kind) => groups.has(kind))
        .map((kind) => `### ${kind}\n\n${groups.get(kind)
          .sort((a, b) => a.title.localeCompare(b.title))
          .map((o) => o.line).join('\n')}`)
      if (deprecatedPages.length) {
        sections.push(`### Deprecated\n\n<div class="text-sm">\n\n${deprecatedPages
          .sort((a, b) => a.title.localeCompare(b.title))
          .map((o) => o.line).join('\n')}\n\n</div>`)
      }
      if (sections.length) {
        page.content += `\n## In this package\n\n${sections.join('\n\n')}\n`
      }
    }

    for (const page of this.apiPages) {
      mkdirp.sync(path.dirname(page.destination))
      fs.writeFileSync(page.destination, page.frontmatter + page.content)
    }
  }
}

export { DruxtDocgen }
