const bodyParser = require('body-parser')
const app = require('express')()
const fs = require('fs')
const launch = require('launch-editor')
const { kebabCase } = require('scule')

app.use(bodyParser.json())

app.post('/add', async (req, res) => {
  const { path, settings } = req.body
  if (!path) throw new Error('Missing required path attribute.')

  const prefix = kebabCase(settings.component).replace('-', '/') + '/'
  const dest = 'components/' + path.replace(settings.component, prefix) + '.vue'
  const dir = `components/${prefix}`

  let imports = ''
  let exports = []
  if (settings.mixins) {
    imports = Object.entries(settings.mixins).map(([mixin, module]) => `import { ${mixin} } from '${module}'\r\n`) + '\r\n'
    const mixins = Object.keys(settings.mixins).map((mixin) => mixin)
    exports.push(`  mixins[${mixins.join(', ')}]`)
  }
  else if (settings.props) {
    exports = [
      '  data: ({ value }) => ({ model: value }),',
      '  props: [',
      ...settings.props.map((o) => `    '${o.key}',`),
      '  ]'
    ]
  }
  exports = '\r\n' + exports.join('\r\n')

  const template = `<!-- Generated by the Druxt devel template server middleware. -->
<template>
  <div>
    <DruxtDebug :json="${settings.debug || 'model'}" />
  </div>
</template>

<script>
${imports}export default {${exports}}
</script>
`
  await fs.promises.mkdir(dir, { recursive: true })
  fs.writeFile(dest, template, (err) => {
    if (err) throw err
    launch(dest)
    res.json({ file: dest })
  })
})

module.exports = app
